# Generated by Django 2.2.7 on 2019-11-12 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('genre', models.TextField()),
                ('runtime', models.TimeField(verbose_name='%H%M')),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('purchased_at', models.DateTimeField()),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Showing')),
            ],
        ),
    ]
