# Generated by Django 2.2.7 on 2019-11-12 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.TextField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.TextField(verbose_name='%H%M'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='showtime',
            field=models.TextField(),
        ),
    ]
